spring:
  # Server Configuration
  server:
    port: 8080

  # DataSource Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Using 'validate' since Flyway will handle schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    validate-on-migrate: true
    table: flyway_schema_history

management:
  endpoint:
    health:
      # Expose liveness a readiness urls /actuator/health/liveness, /actuator/health/readiness.
      probes:
        enabled: true
      group:
        readiness:
          include: db, readinessState
        liveness:
          include: db, livenessState
  health:
    indicators:
      db:
        enabled: true
      readinessState:
        enabled: true
      livenessState:
        enabled: true

# Logging
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.flywaydb: INFO
    com.jumpsoft:
      taskmanagement: DEBUG
      taskmanagement.controller: DEBUG
      taskmanagement.service: DEBUG
      taskmanagement.repository: DEBUG

