#!/bin/bash
set -e

export PGPASSWORD=${POSTGRES_PASSWORD}
psql -h postgres -p 5432 -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} -d postgres <<-EOSQL
	CREATE USER ${TASKMANAGEMENT_DB_USER} WITH PASSWORD '${TASKMANAGEMENT_DB_PASSWORD}';
	CREATE DATABASE ${TASKMANAGEMENT_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${TASKMANAGEMENT_DB} TO ${TASKMANAGEMENT_DB_USER};
	ALTER DATABASE ${TASKMANAGEMENT_DB} OWNER TO ${TASKMANAGEMENT_DB_USER};
EOSQL
